version: '3'
services:
  nginx:
    container_name: nginx
    image: staticfloat/nginx-certbot
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      CERTBOT_EMAIL: birken1018@gmail.com
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
      - /home/project/frontend/fintake/dist:/usr/share/nginx/html/fintake
      - /home/project/backend/covid-19_api/build/docs/asciidoc:/usr/share/nginx/html/covid19-api
      - /home/project/frontend/covid19/dist/:/usr/share/nginx/html/covid19
    networks:
      - fintake-backend-dev
      - covid19-backend-prd

volumes:
    letsencrypt:

networks:
  fintake-backend-dev:
    external: true
  covid19-backend-prd:
    external: true
